OokmaKyi/urls.py
from django.contrib import admin
from django.urls import path
# Use include() to add URLS from the applications and authentication system
from django.urls import include

# development use only
from django.conf import settings
from django.conf.urls.static import static

from pages.views import page_view
from profiles.views import signup_view

urlpatterns = [
    path('', page_view, name="site_index"),
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', signup_view, name='signup'),
    path('accounts/profile/', include('profiles.urls')),
    path('characters/', include('characters.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)    # development use

characters/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.character_list_view, name='characters_index'),
    path('create/', views.create_character_view, name='create_character'),
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.page_view, name='index'),
]

profiles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profile_view, name='user_profile'),
    path('update_notifications', views.update_notification_preference_view, name='change_notification_preferences'),
]

characters/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Character(models.Model):
    """Model representing a single user's character."""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(
        max_length=32,
        help_text="Enter a name for your character. Warning this cannot be changed latter!")
    xp = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(9999999)])
    belt = models.ForeignKey('Belt', null=True, blank=True, on_delete=models.CASCADE)
    wins = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(999999)])
    loses = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(999999)])
    draws = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(999999)])


class Belt(models.Model):
    name = models.CharField(
        max_length=32,
        help_text="Belt name"
    )
    belt_image = models.ImageField(upload_to='belts/')
    min_xp = models.PositiveIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(9999999)],
        help_text="Minimum xp required to obtain belt, 0 for first belt")
    max_xp = models.PositiveIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(9999999)],
        help_text="Maximum xp for belt")

pages/models.py
from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.
class Page(models.Model):
    """Model representing a single page."""

    """The page slug, which is used to create url's ex(pages/<slug>)."""
    slug = models.CharField(
        unique=True,
        max_length=20,
        help_text="Enter the slug of the page, this will be the url. Must be unique."
    )

    """The page's title."""
    title = models.CharField(
        max_length=65,
        help_text="Enter the title of the page."
    )

    """The body of the page, with html enabled minus script tags"""
    body = RichTextField(
        help_text="Enter the body of the page, html is allowed"
    )

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.slug

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Profile(models.Model):
    """Model representing a single user profile."""

    """The users notification preference, if true will send notifications to the user."""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    notification_preference = models.BooleanField(
        default=False,
        help_text="If ticked will send you notifications."
    )


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

characters/forms.py
from characters.models import Character
from django.forms import ModelForm
from django import forms


class CreateCharacterForm(ModelForm):
    name = forms.CharField(
        max_length=32,
        help_text='Enter a name for your character. Warning this cannot be changed latter!')

    class Meta:
        model = Character
        fields = ['name']

profiles/forms.py
from profiles.models import Profile
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UpdateNotificationPreferenceForm(ModelForm):
    """
    A form that lets a user change their notification preferences.
    """
    class Meta:
        model = Profile
        fields = ['notification_preference']

characters/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render

from characters.forms import CreateCharacterForm


# Create your views here.
@login_required
def character_list_view(request):
    user = request.user
    return render(request, 'characters/characters.html', context={'user': user})


@login_required()
def create_character_view(request):
    """View function for user to create a character."""
    if request.method == "POST":
        form = CreateCharacterForm(request.POST)
        if form.is_valid():
            character = form.save(commit=False)
            character.user = request.user
            character.save()
            return HttpResponseRedirect("/characters/")
    else:
        form = CreateCharacterForm()
        return render(request, "characters/create_character_form.html", {'form': form})

pages/views.py
from django.shortcuts import render, get_object_or_404


# Create your views here.
from .models import Page


def page_view(request, slug="index"):
    """View function for home page of site."""
    if slug == "index":
        index_available = Page.objects.filter(slug='index').count()
        if index_available == 0:
            return render(request, 'pages/default.html')
    page = get_object_or_404(Page, slug=slug)
    return render(request, 'pages/page.html', context={'page': page})

profiles/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render

from profiles.forms import SignupForm, UpdateNotificationPreferenceForm


# Create your views here.
def signup_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect("/")
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return HttpResponseRedirect("/")
    else:
        form = SignupForm()
    return render(request, 'profiles/signup_form.html', {'form': form})


@login_required
def profile_view(request):
    """View function for user profiles."""
    user = request.user
    return render(request, 'profiles/profile.html', context={'user': user})


@login_required
def update_notification_preference_view(request):
    """View function for user to change email."""
    if request.method == "POST":
        form = UpdateNotificationPreferenceForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/accounts/profile/")
    else:
        form = UpdateNotificationPreferenceForm(instance=request.user.profile)
        return render(request, "profiles/update_notification_preference_form.html", {'form': form})

templates/base_footer.html
<footer>Powered by Django</footer>

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_header.html" %}
    {% block title %}<title>Ookma-Kyi</title>{% endblock %}
</head>
<body>
    <div class="container">{% block content %}{% endblock %}</div>
    {% include "base_footer.html" %}{% load static %}
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.slim.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/base_header.html
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootswatch-superhero.min.css' %}">

templates/characters/characters.html
{% extends 'base_generic.html' %}

{% block title %}<title>Your Characters</title>{% endblock %}

    {% block content %}
        <div class="row mt-5">
  <div class="col-md-6 m-auto">
    <div class="card card-body">
      <h1 class="text-center mb-3">
          <i class="fas fa-fist-raised" aria-hidden="true"></i>  Characters
      </h1>
        {% if user.character_set.count == 0 %}
            <p>You have no characters, why not create a new character?</p>
            <a href="{% url 'create_character' %}" class="btn btn-primary" role="button" title="Create a new character">Create a new character</a>
        {% else %}
            <p>Characters</p>
            {% for character in user.character_set.all %}
                <table>
                <tr>
                    <th scope="row">Name:</th><td>{{ character.name }}</td>
                </tr>
                <tr>
                    <th scope="row">Xp:</th><td>{{ character.xp }}</td>
                </tr>
                <tr>
                    <th scope="row">Belt:</th><td>{{ character.belt }}</td>
                </tr>
                <tr>
                    <th scope="row">Wins:</th><td headers="wins">{{ character.wins }}</td>
                </tr>
                <tr>
                    <th scope="row">Loses:</th><td>{{ character.loses }}</td>
                </tr>
                <tr>
                    <th scope="row">Draws:</th><td>{{ character.draws }}</td>
                </tr>
                </table>
            {% endfor %}
        {% endif %}
    </div>
  </div>
</div>
    {% endblock %}

templates/characters/create_character_form.html
{% extends 'base_generic.html' %}

{% block title %}<title>Create a new character</title>{% endblock %}

    {% block content %}
        <div class="row mt-5">
  <div class="col-md-6 m-auto">
    <div class="card card-body">
      <h1 class="text-center mb-3">
          <i class="fas fa-plus" aria-hidden="true"></i>  Create Character
      </h1>
    <form method="post">
    {% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-primary" role="alert">
    {% if form.errors.items|length == 1 %}<p>Please correct the error below.</p>{% else %}<p>Please correct the errors below.</p>{% endif %}
    <ul>
    {% for error in form.name.errors %}
        <li>{{ error }}</li>
    {% endfor %}
    </ul>
    </div>
    {%  endif %}
    <div class="form-group">
    <label for="{{ form.name.id_for_label }}" class="label">Character name</label>
    <input type="text" class="form-control" aria-describedby="nameHelpBlock" id="{{ form.name.id_for_label }}" name="{{ form.name.html_name }}" maxlength="32" placeholder="Enter desired character name" autofocus required>
    <span id="nameHelpBlock" class="form-text text-muted">{{ form.name.help_text }}</span>
    </div>
    <button type="submit" class="btn btn-primary">Create character</button>
    </form>
    </div>
  </div>
</div>
    {% endblock %}

templates/pages/default.html
{% extends "base_generic.html" %}

{% block title %}<title>Default Page</title>{% endblock %}

    {% block content %}
        <h1>Congratulations</h1>
        <p>Your site is up and running!<p>
        <hr>
        <p>If you are seeing this message it means a page with the name index was not found in the database. Log in to
        the administrative panel and create a page with "index" without the quotes, as the slug to dismiss this
        message.</p>
    {% endblock %}

templates/pages/page.html
{% extends "base_generic.html" %}

{% block title %}<title>{{ page.title }}</title>{% endblock %}

    {% block content %}
        {{ page.body | safe }}
    {% endblock %}

templates/profiles/profile.html
{% extends 'base_generic.html' %}

{% block title %}<title>User Profile</title>{% endblock %}

    {% block content %}
        <div class="row mt-5">
  <div class="col-md-6 m-auto">
    <div class="card card-body">
      <h1 class="text-center mb-3">
          <i class="fas fa-user-alt" aria-hidden="true"></i>  Profile
      </h1>
        <ul>
            <li>Username: {{ user.username }}</li>
            <li>Password: ****** <a href="{% url 'password_change' %}">Change password</a></li>
            <li>Email: {{ user.email }}</li>
            <li>Notifications: {% if user.profile.notification_preference %}Allow{% else %}Deny{% endif %} <a href="{% url 'change_notification_preferences' %}">Update notification preference</a></li>
        </ul>
    </div>
  </div>
</div>
    {% endblock %}

templates/profiles/signup_form.html
{% extends 'base_generic.html' %}

{% block title %}<title>Register new account</title>{% endblock %}

{% block content %}
  <div class="row mt-5">
  <div class="col-md-6 m-auto">
    <div class="card card-body">
      <h1 class="text-center mb-3">
          <i class="fas fa-pen-alt" aria-hidden="true"></i>  Register
      </h1>
  <form method="post">
    {% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-primary" role="alert">
    {% if form.errors.items|length == 1 %}<p>Please correct the error below.</p>{% else %}<p>Please correct the errors below.</p>{% endif %}
    <ul>
    {% for error in form.username.errors %}
        <li>{{ error }}</li>
    {% endfor %}
    {% for error in form.email.errors %}
        <li>{{ error }}</li>
    {% endfor %}
    {% for error in form.password1.errors %}
        <li>{{ error }}</li>
    {% endfor %}
    {% for error in form.password2.errors %}
        <li>{{ error }}</li>
    {% endfor %}
    </ul>
    </div>
    {%  endif %}
    <div class="form-group">
    <label for="{{ form.username.id_for_label }}" class="label">Username</label>
    <input type="text" class="form-control" aria-describedby="usernameHelpBlock" id="{{ form.username.id_for_label }}" name="{{ form.username.html_name }}" maxlength="150" placeholder="Enter desired username" autofocus required>
    <span id="usernameHelpBlock" class="form-text text-muted">{{ form.username.help_text }}</span>
    </div>
    <div class="form-group">
    <label for="{{ form.email.id_for_label }}" class="label">Email</label>
    <input type="text" class="form-control" aria-describedby="emailHelpBlock" id="{{ form.email.id_for_label }}" name="{{ form.email.html_name }}" maxlength="254" placeholder="Enter you email address" required>
    <span id="emailHelpBlock" class="form-text text-muted">{{ form.email.help_text }}</span>
    </div>
    <div class="form-group">
    <label for="{{ form.password1.id_for_label }}" class="label">Password</label>
    <input type="password" class="form-control" aria-describedby="password1HelpBlock" id="{{ form.password1.id_for_label }}" name="{{ form.password1.html_name }}" placeholder="Enter password" required>
    <span id="password1HelpBlock" class="form-text text-muted">{{ form.password1.help_text }}</span>
    </div>
    <div class="form-group">
    <label for="{{ form.password2.id_for_label }}" class="label">Verify Password</label>
    <input type="password" class="form-control" aria-describedby="password2HelpBlock" id="{{ form.password2.id_for_label }}" name="{{ form.password2.html_name }}" placeholder="Confirm your password" required>
    <span id="password2HelpBlock" class="form-text text-muted">{{ form.password2.help_text }}</span>
    </div>
    <button type="submit" class="btn btn-primary btn-block">Sign up</button>
  </form>
    </div>
  </div>
</div>
{% endblock %}

templates/profiles/update_notification_preference_form.html
{% extends "base_generic.html" %}

{% block title %}<title>Update notification preferences</title>{% endblock %}

    {% block content %}
        <div class="row mt-5">
  <div class="col-md-6 m-auto">
    <div class="card card-body">
      <h1 class="text-center mb-3">
          <i class="fas fa-user-alt" aria-hidden="true"></i>  Notifications
      </h1>
{% if form.errors %}
<p>An error occurred with your request. Please try again latter.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
{% else %}
        <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form action="{% url 'change_notification_preferences' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
    <label for="{{ form.notification_preference.id_for_label }}" class="label">Allow Notifications?</label>
    <input type="checkbox" class="form-control" id="{{ form.notification_preference.id_for_label }}" name="{{ form.notification_preference.html_name }}" {% if user.profile.notification_preference %}checked{% endif %}>
    </div>
    <button type="submit" class="btn btn-primary btn-block">Change</button>
</form>
    </div>
  </div>
</div>
    {% endblock %}